// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheerController from "./cheer_controller"
application.register("cheer", CheerController)

import ConfettiController from "./confetti_controller"
application.register("confetti", ConfettiController)

import GaugeController from "./gauge_controller"
application.register("gauge", GaugeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
